=== ciwise/ciwise-accounts/src/main/resources/account-entries.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "acct_id": {
        "type": "string"
      },
      "coa_id": {
        "type": "string"
      },
      "desc": {
        "type": "string"
      },
      "trans_date": {
        "type": "string"
      },
      "debit": {
        "type": "string"
      },
      "credit": {
        "type": "string"
      },
      "rec": {
        "type": "integer"
      }
    },
    "required": [
      "id",
      "acct_id",
      "coa_id",
      "desc",
      "trans_date",
      "debit",
      "credit",
      "rec"
    ]
  }
}

=== ciwise/ciwise-accounts/src/main/resources/account-entries.json
[
	{
		"id":"1",
		"acct_id": "1",
		"coa_id": "500",
		"desc": "Cash deposit-Capital",
		"trans_date": "07/31/2016",
		"debit": "100.00",
		"credit": "",
		"rec": 0
	},
	{
		"id":"2",
		"acct_id": "1",
		"coa_id": "500",
		"desc": "Receivable-Hoegg Software",
		"trans_date": "08/02/2016",
		"debit": "800.00",
		"credit": "",
		"rec": 0
	}
]
